/**
 * PDF Export System for LearnAI
 * Exports flashcards and questions to printable PDF
 */

import type { StudyBank } from '../types/index';

export function exportToPDF(bank: StudyBank, options: {
  includeFlashcards?: boolean;
  includeQuiz?: boolean;
  includeFillBlanks?: boolean;
  includeShortAnswers?: boolean;
  showAnswers?: boolean;
} = {}): void {
  const {
    includeFlashcards = true,
    includeQuiz = true,
    includeFillBlanks = true,
    includeShortAnswers = true,
    showAnswers = true
  } = options;

  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export PDF');
    return;
  }

  const styles = `
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { 
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        padding: 40px;
        max-width: 800px;
        margin: 0 auto;
        color: #1a1a2e;
        line-height: 1.6;
      }
      .header {
        text-align: center;
        margin-bottom: 40px;
        padding-bottom: 20px;
        border-bottom: 3px solid #6366f1;
      }
      .header h1 {
        font-size: 28px;
        color: #6366f1;
        margin-bottom: 8px;
      }
      .header p {
        color: #64748b;
        font-size: 14px;
      }
      .section {
        margin-bottom: 40px;
        page-break-inside: avoid;
      }
      .section-title {
        font-size: 20px;
        color: #6366f1;
        margin-bottom: 20px;
        padding-bottom: 10px;
        border-bottom: 2px solid #e2e8f0;
        display: flex;
        align-items: center;
        gap: 10px;
      }
      .section-title .icon {
        width: 28px;
        height: 28px;
        background: linear-gradient(135deg, #6366f1, #8b5cf6);
        border-radius: 6px;
        display: flex;
        align-items: center;
        justify-content: center;
        color: white;
        font-size: 14px;
      }
      .card {
        background: #f8fafc;
        border: 1px solid #e2e8f0;
        border-radius: 8px;
        padding: 16px;
        margin-bottom: 12px;
        page-break-inside: avoid;
      }
      .card-number {
        font-size: 12px;
        color: #6366f1;
        font-weight: 600;
        margin-bottom: 8px;
      }
      .question {
        font-weight: 600;
        color: #1e293b;
        margin-bottom: 8px;
      }
      .answer {
        color: #059669;
        background: #ecfdf5;
        padding: 8px 12px;
        border-radius: 4px;
        border-left: 3px solid #059669;
      }
      .answer.hidden {
        color: transparent;
        background: #f1f5f9;
        border-left-color: #94a3b8;
      }
      .answer.hidden::after {
        content: '(Answer hidden - for self-testing)';
        color: #94a3b8;
        font-style: italic;
      }
      .options {
        margin: 12px 0;
      }
      .option {
        padding: 8px 12px;
        margin: 4px 0;
        background: white;
        border: 1px solid #e2e8f0;
        border-radius: 4px;
        display: flex;
        gap: 10px;
      }
      .option.correct {
        background: #ecfdf5;
        border-color: #059669;
      }
      .option-letter {
        font-weight: 600;
        color: #6366f1;
        min-width: 24px;
      }
      .footer {
        margin-top: 40px;
        padding-top: 20px;
        border-top: 1px solid #e2e8f0;
        text-align: center;
        color: #94a3b8;
        font-size: 12px;
      }
      @media print {
        body { padding: 20px; }
        .card { break-inside: avoid; }
        .no-print { display: none; }
      }
      .print-btn {
        position: fixed;
        top: 20px;
        right: 20px;
        background: linear-gradient(135deg, #6366f1, #8b5cf6);
        color: white;
        border: none;
        padding: 12px 24px;
        border-radius: 8px;
        font-size: 16px;
        cursor: pointer;
        display: flex;
        align-items: center;
        gap: 8px;
        box-shadow: 0 4px 12px rgba(99, 102, 241, 0.3);
      }
      .print-btn:hover {
        transform: translateY(-2px);
        box-shadow: 0 6px 16px rgba(99, 102, 241, 0.4);
      }
    </style>
  `;

  let content = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${bank.fileName} - LearnAI Export</title>
      ${styles}
    </head>
    <body>
      <button class="print-btn no-print" onclick="window.print()">
        🖨️ Print / Save PDF
      </button>
      
      <div class="header">
        <h1>📚 ${bank.fileName}</h1>
        <p>Generated by LearnAI • ${new Date().toLocaleDateString()}</p>
        <p style="margin-top: 8px; color: #6366f1;">learnusingai.vercel.app</p>
      </div>
  `;

  // Flashcards
  if (includeFlashcards && bank.flashcards.length > 0) {
    content += `
      <div class="section">
        <h2 class="section-title">
          <span class="icon">🎴</span>
          Flashcards (${bank.flashcards.length})
        </h2>
    `;
    bank.flashcards.forEach((card, index) => {
      content += `
        <div class="card">
          <div class="card-number">Flashcard #${index + 1}</div>
          <div class="question">Q: ${escapeHtml(card.question)}</div>
          <div class="answer ${showAnswers ? '' : 'hidden'}">A: ${showAnswers ? escapeHtml(card.answer) : ''}</div>
        </div>
      `;
    });
    content += '</div>';
  }

  // MCQs
  if (includeQuiz && bank.mcqs.length > 0) {
    content += `
      <div class="section">
        <h2 class="section-title">
          <span class="icon">✓</span>
          Multiple Choice Questions (${bank.mcqs.length})
        </h2>
    `;
    bank.mcqs.forEach((mcq, index) => {
      content += `
        <div class="card">
          <div class="card-number">Question #${index + 1}</div>
          <div class="question">${escapeHtml(mcq.question)}</div>
          <div class="options">
      `;
      mcq.options.forEach((option, optIndex) => {
        const letter = String.fromCharCode(65 + optIndex);
        const isCorrect = showAnswers && optIndex === mcq.correctIndex;
        content += `
          <div class="option ${isCorrect ? 'correct' : ''}">
            <span class="option-letter">${letter}.</span>
            <span>${escapeHtml(option)}</span>
            ${isCorrect ? ' ✓' : ''}
          </div>
        `;
      });
      content += '</div></div>';
    });
    content += '</div>';
  }

  // Fill in the blanks
  if (includeFillBlanks && bank.fillBlanks.length > 0) {
    content += `
      <div class="section">
        <h2 class="section-title">
          <span class="icon">✏️</span>
          Fill in the Blanks (${bank.fillBlanks.length})
        </h2>
    `;
    bank.fillBlanks.forEach((item, index) => {
      content += `
        <div class="card">
          <div class="card-number">Question #${index + 1}</div>
          <div class="question">${escapeHtml(item.sentence)}</div>
          <div class="answer ${showAnswers ? '' : 'hidden'}">Answer: ${showAnswers ? escapeHtml(item.answer) : ''}</div>
        </div>
      `;
    });
    content += '</div>';
  }

  // Short Answer / Exam questions
  if (includeShortAnswers && bank.shortAnswers.length > 0) {
    content += `
      <div class="section">
        <h2 class="section-title">
          <span class="icon">📝</span>
          Short Answer Questions (${bank.shortAnswers.length})
        </h2>
    `;
    bank.shortAnswers.forEach((item, index) => {
      content += `
        <div class="card">
          <div class="card-number">Question #${index + 1}</div>
          <div class="question">${escapeHtml(item.question)}</div>
          <div class="answer ${showAnswers ? '' : 'hidden'}">Model Answer: ${showAnswers ? escapeHtml(item.suggestedAnswer) : ''}</div>
        </div>
      `;
    });
    content += '</div>';
  }

  content += `
      <div class="footer">
        <p>Created with LearnAI - Free AI Study Material Generator</p>
        <p>Visit: learnusingai.vercel.app</p>
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(content);
  printWindow.document.close();
}

function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
